#!/bin/bash

export RELION_EXTERNAL_RECONSTRUCT_EXECUTABLE="/mhome/maths/s/sl767/PythonCode/SingleParticleAnalysis/ext_reconstruct_AR.py"
method="AR"

# first argument is noise level, second regularization parameter
reconstruct () {
    export RELION_EXTERNAL_RECONSTRUCT_REGULARIZATION=$2
    python /mhome/maths/s/sl767/PythonCode/SingleParticleAnalysis/ClassFiles/run_external_reconstruction.py $1 '5A0M' "AR" $2
}

reconstruct "01" ".005"
reconstruct "01" ".003"

reconstruct "012" ".01"
reconstruct "012" ".0075"

reconstruct "016" ".015"
reconstruct "016" ".025"

reconstruct "02" ".03"
reconstruct "02" ".05"