#!/bin/bash

export RELION_EXTERNAL_RECONSTRUCT_EXECUTABLE="/mhome/maths/s/sl767/PythonCode/SingleParticleAnalysis/ext_reconstruct_AR.py"
source activate py3

echo -e "Please enter the noise level. Currently supported values are 01, 013, 016 and 02 "
read noise_level

python /mhome/maths/s/sl767/PythonCode/SingleParticleAnalysis/ClassFiles/run_external_reconstruction.py $noise_level '5A0M'
