#!/bin/bash

export RELION_EXTERNAL_RECONSTRUCT_EXECUTABLE="/home/zickert/SingleParticleAnalysis/LowPassIni/ext_reconstruct_AR.py"
method="AR"

# first argument is noise level, second regularization parameter, third PDB ID, fourth GPU_ids
reconstruct () {
    export RELION_EXTERNAL_RECONSTRUCT_REGULARIZATION=$2
    python /home/zickert/SingleParticleAnalysis/LowPassIni/run_external_reconstruction.py $1 $3 "AR" $2 $4
}

reconstruct "01" "0.0" 6A0J "4:5"
#reconstruct "01" "0.6" 6A0J
#reconstruct "01" "1.0" 6A0J "4:5"
#reconstruct "01" "2.0" 6A0J
#reconstruct "01" "5.0" 6A0J
#reconstruct "01" "10.0" 6A0J "4:5"
#reconstruct "01" "50.0" 6A0J

#reconstruct "012" "0.0" 6A0J
#reconstruct "012" "1.5" 6A0J
#reconstruct "012" "2.0" 6A0J
#reconstruct "012" "20.0" 6A0J

#reconstruct "016" "0.0" 6A0J
#reconstruct "016" "3.0" 6A0J
#reconstruct "016" "5.0" 6A0J
#reconstruct "016" "30.0" 6A0J

#reconstruct "02" "0.0" 6A0J
#reconstruct "02" "6.0" 6A0J
#reconstruct "02" "10.0" 6A0J
#reconstruct "02" "100.0" 6A0J