#!/bin/bash
source activate tf36

python run_relion_stuff.py --projs 1 --em 1 --gpu 0:1 --pdb_folder 1 --pdb_id 0 --noise "01 02" --ext 0 --eval 0 --pdb_start_idx 0 --pdb_end_idx 15
python run_relion_stuff.py --projs 1 --em 1 --gpu 0:1 --pdb_folder 2 --pdb_id 0 --noise "01 02" --ext 0 --eval 0 --pdb_start_idx 0 --pdb_end_idx 15
python run_relion_stuff.py --projs 1 --em 1 --gpu 0:1 --pdb_folder 3 --pdb_id 0 --noise "01 02" --ext 0 --eval 0 --pdb_start_idx 0 --pdb_end_idx 15

