#!/bin/bash

export RELION_EXTERNAL_RECONSTRUCT_EXECUTABLE="/mhome/maths/s/sl767/PythonCode/SingleParticleAnalysis/Paper/ext_reconstruct_ONLY_TIKHONOV_paper.py"
#method="AR"

# first argument is noise level, second regularization parameter
reconstruct () {
    export RELION_EXTERNAL_RECONSTRUCTION_TIK_REG=$2
    python /mhome/maths/s/sl767/PythonCode/SingleParticleAnalysis/Paper/run_external_reconstruction_paper_ONLY_TIKHONOV.py $1 '5A0M' "ONLY_TIKHONOV" $2
}

reconstruct "01" "1e4"
reconstruct "01" "1e5"
reconstruct "01" "1e6"
reconstruct "01" "1e7"
reconstruct "01" "1e8"
reconstruct "01" "1e9"

#reconstruct "012" "0.0"
#reconstruct "012" "1.5"
#reconstruct "012" "2.0"
#reconstruct "012" "20.0"

#reconstruct "016" "0.0"
#reconstruct "016" "3.0"
#reconstruct "016" "5.0"
#reconstruct "016" "30.0"

#reconstruct "02" "0.0"
#reconstruct "02" "6.0"
#reconstruct "02" "10.0"
#reconstruct "02" "100.0"